### ISSUE TITLE
Survey Updates

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#102]
**Items Needed**
--------------------
- [x] Terms of service text
- [x] For each survey page about, do you want to require the user to select a value for all fields.  A few pictures mark fields as required, while some other pictures do not.    The only optional question I can see is the 4th question on the first survey page.   **This was put on hold pending the new questions**
- [x] Do you need a button to export survey results to a csv file?
- [x] List of questions and possible answers for the survey and/or follow up survey
 The rest should be required? Please confirm this is what you would like?
- [x] Do you want a confirmation email to be sent (to the user) when a user submits a survey or is a simple notification in the web application sufficient? **YES**
- [x] Do you want a confirmation email to be sent to someone other than the user when a user submits a survey?  If so, let me know who to send this to? **YES**

**Tasks**
--------------------
**(4 hours) Database & Misc Updates**
- [x] Define survey schema for tracking survey results
- [x] Add table, connect to web application.
- [x] Add use survey hook and connect create & read logic.
- [x] Add banner/notification at the top of the application page which allows the user to click to participate in a survey.
- [x] Create follow up email template and connect to admin table.  Incorporate surveyParentId, lastReminderSent so we can track completion states of follow ups and completed follow-up surveys.

**(4 hours) Automated Email Reminder**
- [x] Implement AWS task schedule to automatically send out email reminders for follow up survey reminders.

**(16 hours) Survey Page - Shows the visual survey elements and allows the user to complete survey questions.**
- [x] Agreement to terms of service
- [x] Implement updates and corrections to survey questions (as defined in screenshots below)
- [x] Add validations for required fields
- [x] Allow direct link into survey so it can be clicked from an email and linked to follow up email
- [x] Add any necessary email notifications upon completion of survey
- [x] Notify user in web app when survey is complete
- [x] Notify user via email when survey is complete
- [x] Notify admin user via email when a user completes a survey (make this configurable in the package.json file, current value: ecamach1@bidmc.harvard.edu)
- [x] Create survey question input components (text input, 1 to 5 rating, yes/no, etc)
- [x] Link selected application to survey schema
- [x] Link survey schema to visual components
- [x] Implement step logic. Add validation, and submit placeholders.
- [x] Create Survey Page 1
- [x] Create Survey Page 2
- [x] Create Survey Page 3
- [x] Create Survey Page 4
- [x] Create Survey Page 5
- [x] Implement submit logic
- [x] Update survey and add new questions as described in: https://docs.google.com/document/d/1a1Sbr4_WHVER5-BToz6wFyv6OPTfg55C/edit?usp=sharing&ouid=112506938105230622159&rtpof=true&sd=true

**(8 hours) Admin Survey Tab**
- [x] Add ability for multiple follow up surveys.
- [x] Show survey follow up week/number in the table as well as the export.
- [x] Add export button
- [x] Add column indicating if follow up survey has been completed.
- [x] Add a survey tab for admin
- [x] Add table showing each complete survey as a row
- [x] Add ability to view/load individual survey data by viewing answers
- [x] Add "Send Follow Up Email" button.  
- [x] Add column indicating when last follow up email has been sent.

**Comment by ecamach13** [comment]
For the terms of service this is along the lines of what I imagine: 

Please download this informed consent and terms of agreement here: (insert link here)

- [ ]  I have read the informed consent document and I consent to partaking in this study. 
- [ ] I acknowledge and understand if I experience a clinical emergency, I must independently contact my local hospital or dial 911.

By typing your name below, you are signing this application electronically. You agree that your electronic signature is the legal equivalent of your manual signature on this application. 
- place to sign and date

- make everything above required in order to continue

**Comment by ecamach13** [comment]
There will be 5 'surveys' for them to complete. If you could include something at the bottom like 5 blank bubbles that get filled in as they move along or 1/5 etc that would be great. I've attached the 5 images of the surveys we'd like to include. 

<img width="803" alt="Screen Shot 2021-09-24 at 9 35 06 AM" src="https://user-images.githubusercontent.com/70787908/134683823-bf7d8652-0782-4dea-940b-e0f48ec2defd.png">
<img width="799" alt="Screen Shot 2021-09-24 at 9 30 58 AM" src="https://user-images.githubusercontent.com/70787908/134683833-d3bbe4ea-8419-48ad-b1ba-3f8c962898ca.png">
<img width="798" alt="Screen Shot 2021-09-24 at 9 31 48 AM" src="https://user-images.githubusercontent.com/70787908/134683836-5cf51d5a-dffa-4a24-8219-4c9de67e67fd.png">
<img width="598" alt="Screen Shot 2021-09-24 at 9 35 30 AM" src="https://user-images.githubusercontent.com/70787908/134683840-dce0c7cc-449e-4d49-94aa-b627731ded49.png">

- instead of saying "recommended app" it should read "the app I selected"

<img width="600" alt="Screen Shot 2021-09-24 at 9 35 40 AM" src="https://user-images.githubusercontent.com/70787908/134683842-520df7c1-ba5f-4ed8-931c-5f0de186f9b6.png">

**Comment by ecamach13** [comment]
The follow up surveys will be the exact same surveys sent at 2 weeks out and then 4 weeks out from the 2 week survey.

**Comment by cvanem** [comment]
@ecamach13 Ok, can you also provide the possible answer values for the two drop down questions in the 1st picture?

**Comment by ecamach13** [comment]
for gender: 
- prefer not to say 
- female
- male 
- gender non-binary 
- other

for describe yourself: 
- 
<img width="238" alt="Screen Shot 2021-09-24 at 12 56 34 PM" src="https://user-images.githubusercontent.com/70787908/134712977-63a8b302-14d4-4f7a-b231-0819015aab16.png">

**Comment by cvanem** [comment]
@ecamach13 I am making decent progress.  Probably about 60-70% done.

I added a few outstanding questions to the Items Needed list in the first post.  Please review when you get a minute.  Thanks!

**Comment by ecamach13** [comment]
For each survey page about, do you want to require the user to select a value for all fields. A few pictures mark fields as required, while some other pictures do not. The only optional question I can see is the 4th question on the first survey page.
The rest should be required? Please confirm this is what you would like?
- hold off on this until I send the changes 

 Do you want a confirmation email to be sent (to the user) when a user submits a survey or is a simple notification in the web application sufficient?
- let's do both a notification and a short confirmation email (if the email is easy to implement)
- The email can read: 

Hi, 

Thank you for agreeing to participate in our study! We look forward to hearing your thoughts about this app. If you have any questions regarding this study, please contact Erica Camacho at ecamach1@bidmc.harvard.edu.

Best, 
The Division of Digital Psychiatry 


 Do you want a confirmation email to be sent to someone other than the user when a user submits a survey? If so, let me know who to send this to?
- Yes, It should go to my email ecamach1@bidmc.harvard.edu
- Can this easily be changed in the future? If not I would need to reconsider whose email to send it to.

**Comment by ecamach13** [comment]
For the terms of service text, we will have to write up a new IRB and new informed consent document. Once that's approved I will have a document for you to upload.

**Comment by ecamach13** [comment]
Terms of service text
- 

 For each survey page about, do you want to require the user to select a value for all fields. A few pictures mark fields as required, while some other pictures do not. The only optional question I can see is the 4th question on the first survey page. This was put on hold pending the new questions
- [x] yes, all questions should be required except ones that say "if yes, then..."

 Do you need a button to export survey results to a csv file?
- yes & when it exports can you have it say whether it is survey 1, 2, or 3 instead of true or false for whether it's a follow-up survey. The current setup doesn't allow us to differentiate between visit 2 or 3 without checking the dates.

 List of questions and possible answers for the survey and/or follow up survey
The rest should be required? Please confirm this is what you would like?
- here are some changes to the survey questions: 

- Demographics
- [x] 1. Change African American to Black or African American
- [x] 2. Remove "is this your first time attending therapy" question

- Technology usage
- [x] 1. Add question mark to end of "How comfortable are you downloading an app from the app store"

- Access to Health 
- [x] 1. Add colon to end of the phrase 'access to health' so it matches the other headers

- App Selection Information
- [x] 1. Change title to "App Selection"
- [x] 2. Add colon to end of the phrase 'App Selection' so it matches the other headers

- (no name / title for this page) 
- [x] 1. Name this 'System Usability Scale:'
- [x] 2. We are reducing the number of questions to just 4: 
- [x]  a) I think that I would like to use this app frequently.
- [x]  b) I think that I would need the support of a technical person to be able to use this app.
- [x]  c) I felt very confident using this app.
- [x]  d) I needed to learn a lot of things before I could get going with this app.
- [x] 3. Add a N/A to these questions for those that are completing survey 1 since they can't answer these questions before utilizing the app

- [x] - (no name / title for this page) 
- [x] 1. Name this 'Digital Working Alliance Inventory:'
- [x] 2. Add a N/A to these questions for those that are completing survey 1 since they can't answer these questions before utilizing the app

- [x] - (no name / title for this page) 
- [x] 1. Name this 'General Self-Efficacy Scale-6:'
- [x] 2. We would like to reduce this survey from the original 10 questions to 6. The questions with an asterisk are to be included. See image below:
![image](https://user-images.githubusercontent.com/70787908/145473422-e5eaa5de-2440-456c-9e42-c7acac82cabc.png)

**Comment by ecamach13** [comment]
John wanted to know if instead of us clicking 'send followup reminder' at 2 and 4 week mark, if this could be automated? If so, how long / how much would this take?

**Comment by ecamach13** [comment]
For the Terms of Service text, there should be either a page zero with this paragraph on it, or at the top of the first set of survey questions this paragraph should appear. 

- Thank you for your interest in completing our survey! The surveys will take less than 10 minutes to complete total. You will be asked to complete these surveys three times over the course of six weeks. Once now, once two weeks from now, and once four weeks from the two week mark (i.e. six weeks from now). By completing the following surveys, you are granting consent to use your anonymous survey information.

**Comment by cvanem** [comment]
@ecamach13 Thanks for the review/updates.  I will add the necessary tasks to the checklist.  I also need to update the code to allow for two follow up surveys instead of just one.  I must have missed that revision initially.

For the automated reminders, we currently don't have anything in place that does this.  In order for reminders to be sent automatically, code needs to execute repeatedly on the server.  I took a quick look and I think we can use AWS scheduled tasks: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduled_tasks.html.

Essentially we would just create a task that runs once every day.  It would look for all surveys that have been completed and have not had a follow up request sent and send the email if necessary.  I have never used one of these before but it doesn't look too hard.  The task would just need to be created and the existing email logic/credentials and database access tied in somehow.  It is probably a 4-5 hour project.

**Comment by cvanem** [comment]
**Completed:** 
Survey question/answer revisions have been completed.

Terms of Service agreement has been added to the initial survey.  This does not show up on follow up surveys.

Not applicable options are available during the initial survey for steps System Usability Scale and Digital Working Alliance Inventory.  During follow up surveys, not applicable is not available.

**Left to do:**
- [x] Support multiple follow up surveys.
- [x] Differentiate between follow up survey versions for export and table display
- [x] Add survey export
- [x] Automated follow up email reminders via AWS tasks

**Comment by ecamach13** [comment]
Thanks for the update!

**Comment by cvanem** [comment]
The requested revisions have been completed.  AWS has been configured to execute a lambda function every hour which will automatically determine and email a survey reminder if needed.  

The two week reminder will be automatically sent if no prior two week reminders have been sent and two weeks have passed since the initial survey was completed.

The six week reminder will be automatically sent if no prior six week reminders have been sent and four weeks have passed since the two week survey was completed.  

**NOTE: If the user waits a week before completing the two week follow up survey, the six week reminder will be sent out at the 7 week mark, since it uses the most recent survey completion date for reference.**

**Comment by cvanem** [comment]
New Revisions

TODO:
- [x] Instead of 'terms of service' could we rename it 'Participate in Research:'
- [x] For the exporting data, can it export in terms of the order of the questions 
'survey type' can be to the left of the first question 
- [x] there are some columns in the exported file that lists things I'm not sure should be there: 
column H: errors
column AD: parentid
column AG: step
column AM: TOS
column AN: updated
If some of these need to be a part of the export, you can put them to the right of the final column (or really anywhere you see fit as long as it's not in between the questions of the surveys)
- [x] The photo that I attached showcasing 'click here to take a survey', John would like for it to be more bold / noticeable. Ideas: 
have it be a pop-up but also still visible where it is
change the color to something brighter
bold the letters and / or make them bigger
pretty much anything you can think of we are open to!!

**Comment by cvanem** [comment]
@ecamach13 
Revisions have been published.  The export has been enhanced for readability and the survey notice visibility has been enhanced.
