### ISSUE TITLE
First Time Use Instructions

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#106]
**TODO:**
- [x] Create tour architecture.
- [x] Automate scroll to target
- [x] Create steps and associated content
- [x] Make popover mount position configurable.
- [x] Allow an arrow and arrow position to be specified.
- [x] Implement Previous, Next, Close and Done.
- [x] Implement onNext and onPrev.
- [x] Implement & test for mobile view
- [x] Detect first time use and prompt user if they would like to take a tour.
- [x] Add menu option for activating tour after first time use.
- [x] Show step/progress information (1 of x or ... indicator)

**Back Story:**
some instructions for use, kind of like those pop-up instructions that you can click 'next' to walk you through how to use the website. For example, a circle highlighting the 'hamburger / three lines' in the top left corner of the app or an arrow pointing to it with a brief 
description pop-up that explains they should click here to filter through the many apps available. Is this feasible?
