### ISSUE TITLE
2.0 Updates

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#111]
**TODO:**

- [x] First time use instructions (8 hours)
- [x] Quiz (20 hours)
- [x] Disable login button when sign in is in process.
- [x] Testing, misc bug fixes and resolve any additional requests. (8 hours)
- [x] Add a way to delete surveys from the admin menu (2 hours)
- [x] Add team members page to community section
- [x] Add external calendar Link to https://www.sodpsych.org/events (Open new window and navigate to calendar)
- [x] Add a home icon to the left drawer in mobile view.  Currently there is no way to navigate to the home page.
- [x] Un-freeze first column for mobile views. (1 hour)
- [x] Fix scroll refresh/crashing on mobile. (8 hours)
- [x] Add tiled grid scroll view. (8 hours)
- [x] For mobile view, move the platforms selector to the left drawer when screen size is small.
- [x] For mobile view, shrink view mode buttons when screen size is small.
- [x] For mobile view, combine search box and view mode buttons in one line when screen size is small.
