### ISSUE TITLE
Updates (12/7/2022)

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#120]
**TODO**
- [x] Add "cardiovascular health" filter under supported conditions 
- [x] Please revise/add the following questions as filters under the specified category: 
    - [x] Change "Has crisis management feature" to "In the case of an emergency does the app appropriately advise the patient?" and switch the category that this question belongs to from privacy to evidence and clinical foundations. Remove the old question, create a new question under a different category and run a script to transfer the old question answers under the new question.  The new question would be shown under the new category and retain all of the previous answers for all of the previous ratings.  
    - [x] Add "Does the app claim to identify new conditions?" under features. For the abbreviated version of the question (the filter shown in the application library), please put "identify new conditions"
    - [x] Change "Use Warning" to "Claims to Not Replace Care" 
- [x] Can the application library page under grid view be set as the landing page (see screenshot)
![image](https://user-images.githubusercontent.com/24579103/206293686-86ae5e85-7a0a-4b5d-92b4-f64e52772b3b.png)
- [x] Can we integrate the quiz that is currently on the landing page to the application library page (aka the new landing page). The quiz button can be placed right under the search bar  
- [x] Can we replace the four buttons at the bottom of the list of filters (see screenshot) with the interested in being an app rater button and page (see screenshot):
![image](https://user-images.githubusercontent.com/24579103/206293775-5e04f711-c2fc-4024-9ec0-db4f2b9f0efb.png)
- [x] Please change "anonymized/aggregated" to just "aggregated" in both the questions that raters see and the privacy filter that users see 
- [x] Please change "de-identified" to "de-identified/anonymized" in both the questions that raters see and the privacy filter that users see 
- [x] Can we change where the "view additional application info" button in table view brings users? We would like that button to lead users to the large main review of the app that is currently only accessible in grid view.
- [x] When users try to close the list of filters that they previously opened. The website deletes those filters. Can we change it, so users are able to close the list of filters, but still able to keep which filters they checked off? (see screen recording that is attached to email) 
- [x] Inputs and Outputs are not listed as one of the categories on the application library page that users can filter by. Can we please add inputs and outputs to this list of filters.
- [x] Finally, please remove the "calendar" page from the community section.

**Research Needed**
- [x] When an admin edits a reviewer's app rating, it creates a new app rating instead of just editing the existing one. Can we change it, so it doesn't create a new app rating and just edits the existing app rating?

**Comment by cvanem** [comment]
**For this issue, I modified the code to only clear the filters if the user clicks on the X icon.  If the user clicks anywhere else on the title or row, then the filter list will just be closed instead of cleared.**

_When users try to close the list of filters that they previously opened. The website deletes those filters. Can we change it, so users are able to close the list of filters, but still able to keep which filters they checked off? (see screen recording that is attached to email)._
