### ISSUE TITLE
MindApp PWA (Quiz Integration)

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#125]
**Misc TODO Tasks**
- [x] Come up with new logo/image for the PWA app.  This would be shown in the users mobile device on their home screen.
- [x] start thinking of a domain name for the PWA wrapper.  I think something like pwa.mindapps.org would work, or app.mindapps.org.  We will need assistance from your IT department in setting this up and connecting the network records.  Once the domain url is set up, then you can access the PWA in a web browser and install the PWA to the homescreen using the desired url.
- [x] We will also need another github repository setup on the https://github.com/BIDMCDigitalPsychiatry account.  This repository will store the PWA wrapper, which allows the app to be installed on mobile devices.
- [x] We will also need a new Vercel account setup that will host the above wrapper.    I am currently using my personal Github and Vercel accounts to host the PWA wrapper. 
- [x] Add auto scrolling
    - [x] Scroll to top on next/back operations
    - [x] Scroll to top on search/reset operations

**Search Tasks**
- [x] Look into and integrate fuzzy searching by app name to improve search result matching, etc.
- [x] Come up with new interface for using search in the PWA without actually using a search bar and header.  Possibly just add an icon or popup window with search functionality.
- [x] Connect quiz questions to existing filter logic.
- [x] Add ability to view filters in the results header.
- [x] Add ability to perform text search in the results header.

**Quiz Tasks**
- [x] Each question should have a next/back button.  If a question is NOT multiple choice, it can automatically take them to the next screen when an option is selected
- [x] Since the multiple-choice filter behavior will mimic selecting multiple filters on the database, I think we will need to clarify that if the user selects more than one answer in a question (ie. If they select journaling AND mood tracking for coping skills), they are limiting their options to apps that contain BOTH, as opposed to seeing a subset of apps with just journaling, just mood tracking, or both.
- [x] All questions should have the option to be skipped, we can discuss the best way to do this, either: 
- [x] Adding an answer option of "It doesn't matter" or "No preference" (or something along those lines) which results in 0 filter being selected
- [x] Adding a skip button to each question
- [ ] As far as wording and who we address question to (client vs. patient vs. you) - I think this will take some group discussion to finalize. The term client is the most generalizable/applicable to clinicians and other users, so I agree it should be used. That being said, if clinicians are our main market, what is stopping us from using the word patient — definitely something we could use John's/other stakeholder insight on down the line. 

**Result Tasks**
- [x] Create new results page for showing results of quiz questions.  
- [x] Link existing view app pages and results grid with new UI.  Minimize functionality and maximize mobile/tablet UI functionality/performance.

-------------------

**Quiz Questions** 

What type of device do you or your client have? 
- [x] Apple
- [x] Android
- [x] Both

Are you or your client able to pay for an app? 
- [x] No, I am only looking apps that are totally free (no download fee or in app payments) 
- [x] I am okay with paying a download fee, but no other fees 
- [x] I am okay with in app payments 
- [x] It doesn't matter to me
- [x] Is it important to you or your client that the app has a privacy policy? 
- [x] Yes, I only want to be recommended an app with a privacy policy 
- [x] Not necessarily, I am okay with using an app that does not have a privacy policy

Are you looking for an app that targets a specific condition? 
- [x] Not necessarily
- [x] Stress & Anxiety
- [x] Biploar Disorder
- [x] OCD 
- [x] Insomnia
- [x] Substance Use
- [x] (Etc.)

Do you want an app that offers a specific treatment approach? 
Not necessarily 
- [x] Cognitive Behavioral Therapy
- [x] Dialecital Behavioral Therapy
- [x] Acceptance and Commitment Therapy 
- [x] Mindulness
- [x] Exercise

What features/coping skills would benefit you or your client? 
- [x] Nothing in specific
- [x] Journaling
- [x] Medication tracking
- [x] Sleep tracking
- [x] Symptom tracking
- [x] Mood tracking

**Comment by cvanem** [comment]
Example mockups:

![image](https://github.com/user-attachments/assets/1b8d33b2-d150-4a2c-a562-7b00d2dc2f24)

**Comment by cvanem** [comment]
Old Quiz Questions (For Reference): 

![step1](https://github.com/user-attachments/assets/1fc70500-de60-4f5c-899f-8b5d56f4f752)
![step2](https://github.com/user-attachments/assets/7f1b4d1a-4c48-4c2f-85cc-d4f7fd4f2cbb)
![step3](https://github.com/user-attachments/assets/6ea141f4-5c30-4c5d-a607-3a677e8625a8)
![step4](https://github.com/user-attachments/assets/dd64f6b6-56f2-4e54-9010-06352e1408a0)
![step5](https://github.com/user-attachments/assets/15608eec-cf78-43cd-9a06-bd75f1c731cd)
![step6](https://github.com/user-attachments/assets/b3c03c43-6611-4701-8e4e-e375d200a5f1)
![step7](https://github.com/user-attachments/assets/ac28e10e-b1e5-4afd-a29c-fafc6c23147d)
![step8](https://github.com/user-attachments/assets/27d2d68f-88ed-4a06-bc26-4cdeea4c15f4)

**Comment by cvanem** [comment]
- [x] I combined the supporting evidence and crisis support questions into a single question since they share the same filter category and it simplifies the logic.
- [x] For the condition target question, you listed "No Specific Condition" as an option.  This particular filter has a 'Non-Specific' filter option, so selecting No Specific Condition will map to this filter option as opposed to not setting any filter value.  I think we should leave this behavior as I described and then add another Skip button at the top that applies no filters.
- [x] For the "Desired treatment approach" question, you listed "Nothing Specific" as an option.  Selecting this option will correspond to not selecting any filters for the Treatment section.  This particular filter section does not have a "Non-Specific' option, so the result would be selecting no filters.  I think we should either rename this option to Skip or remove it and have the user hit the next button.  Whatever we do, I think it should be similar to the above "No Specific Condition" question logic so we are consistent.  Also, it should be similar to the below question as well.  If we either add a Skip button or remove this option entirely and rely on the user to hit the next button to skip, that would work.  
- [x] The "Feature Included?" question has the same "Nothing Specific option as the above question.  I think we should change this to Skip and apply no filters when this is selected or remove the button entirely.
- [x] The "Desired treatment approach?" question had both an "Acceptance and Commitment" and "Acceptance and Commitment Therapay (ACT)" options. I removed the "Acceptance and Commitment" option as I think these are duplicates?  If not, please let me know which questions correspond to which filters.

**Comment by cvanem** [comment]
- [x] Change skip options to "It doesn't matter" for all questions.
- [x] Make the question stick to the top of the page scroll
- [x] Update Mind image to new non-blurry image
- [x] (Pending) Update features filter to form OR operation instead of AND comparison.  Update features question to support multi-select.
- [x] Add landing page for PWA app:
![Image](https://github.com/user-attachments/assets/ae1cbe96-cb83-4aa8-9e89-c311981ec49e)
- [x] Create vertical/horizontal layouts.  Hide app bar.
- [x] Move back/next buttons next to or below progress bar on questions.
- [x] Hide next button on results view.

**Comment by cvanem** [comment]
New filter/display logic for results display:

**TODO**
- [x] Show all results with any matching filters
- [x] Sort results by number of matching filters
- [x] Add UI display for matches on Grid item (Meets 3/5 of your criteria or 60% match, etc and show corresponding matching filters)
- [x] Only show at matches which match at least 2 criteria (or do a percent, maybe 20% of filters must match to show in the result grid).

**Comment by cvanem** [comment]
- [x] Welcome page pop up 
    - [x] Increase font size of the "Welcome to MINDapps"
    - [x] Increase font size of and "Answer a few questions..." text 
    - [x] Should still be slightly smaller than "Welcome to MINDapps"
    - [x] Add a "Search" button next to the "Start Quiz!" button 
        - [x] Search bar use case for context: Patient tells clinician they are using an app and the clinician wants to learn about the app, so they directly search the name without taking the quiz → we are still toying around of exactly how this should appear on the welcome page, but wanted to pilot it for now
- [x] Make all writing the same font size on question pages, particularly increase font size of... 
    - [x] Instruction text ie. "Select an option to continue"
    - [x] Question X/7 font in the top middle (increase font size)
    - [x] Text on all banner buttons → Restart Quiz, Search, Back, Next
- [x] Disconnect the "restart quiz" and "search" button from the banner at the top
- [x] Results page
    - [x] Shrink each app card slightly so there is more white space behind them → we want to separate them so people know they can click on each one individually
    - [x] Get rid of colored text box behind "X matches" so that it is just the text in white font 
    - [x] Change terminology from "X matches" to "Meets X/X Criteria"
    - [x] Change background color of matching criteria bubbles to green (Right now they are all different colors → every bubble should be the same)
    - [x] Get rid of search bar on results page now that it is on welcome page
    - [x] Change “Is PHI shared” filter name to “PHI shared”
        - [x] This can be changed on MINDapps website as well

**Comment by cvanem** [comment]
- [x] Can you change Search button to say Search Apps
- [x] Can you add an OR between the Start Quiz button and Search Apps button
For this, can you make sure the Start Quiz and Search Apps buttons are the same size and still on the same line.
- [x] I agree the filter chips should stay on the results page so that users can remove them as needed. Can you keep these even if you remove the search bar?
- [x] Ideally, the results page could say: “My Search Criteria:” and then lists the filter tags (same format as the “Meets X/X Criteria” and then filter tags).
- [x] For text box size questions...I think we should go with the easier solution and and just keep the Back/Next buttons a bit smaller throughout. Hopefully by doing this we can have this placement: <Back button on top left side → Question X/X text in middle between buttons→ Next> buttons on the right. If you need to play around with the font size for Question X/X, feel free to do whatever fits/looks best.
- [x] Can we cap the results page at 5 apps ie. someone is never shown more than 5 apps that match/are close to their criteria.
Ideally, these 5 apps could be pulled in order of most similar to their search and most recently updated on MINDapps. Since the database is regularly updated, this would ensure the same apps are not constantly resulting.
- [x] For the search button on the question pages, can you change it say Search Now instead of just Search → we want to more clearly indicate that by pressing it, it will automatically search with the criteria you have inputted.
- [x] On results page, for the blue box that shows “Meet X/X Criteria” —> can you shrink blue box vertically and add more white space between the apps?
- [x] In general, it is still hard to tell that you can click on distinct app pages. Perhaps shrinking the app cards themselves and/or adding a good amount of white space would help indicate this.
- [x] On question 7/7 “Features Included?,” can you align answer text options to the left side of the answer boxes so that the check boxes are aligned?
- [x] On question pages, we are playing around with the idea of changing the question boxes to white with black font and the background of the page a dark blue. I have attached an image to give you an idea of what we mean - but the image is not updated to the top navigation bar, its just to give you an idea of the coloring.
- [x] On the app pages, would it be possible to wrap the text for longer tags in the Ratings and Reviews section for each app? On smaller screens like phones, they often overflow the box that they are in causing the page to scroll horizontally. (See screenshot attached)

**Comment by cvanem** [comment]
- [x] On the landing page, can you add a bit more space between the line under “Welcome to MINDapps” and the overview sentence below the line. Right now that sentence pushes right up against the divider line
- [x] On the landing page, can you make both bottom buttons slightly bigger so “Search Apps” is not pushing against the edges of the box. (Both boxes should still be same size if both are enlarged slightly)
- [x] On question pages, the question itself (ie. Type of device?) seems a little small…I see that the font size is consistent with the other text elements on the screen but the question is kind of hard to notice now. Can you increase the question font size slightly so it stands out more. Maybe bolding it would help as well.
- [x] There are some general glitches → When the app is first opened, the screen goes black for a few seconds, then white for a few seconds. Are you able to fix this?
- [x] When users add the app to the home screen, the suggested app name is “MindApps,” can you change it to auto-populate to “MINDapps”
- [x] When users visit [pwa.mindapps.org](http://pwa.mindapps.org/) … Can you add a pop up that prompts them to add the app to their home screen → similar format to the video that pops up the first time you enter the database... ie. users can X out of it
The popup can read:
Add MINDapps to your home screen! (centered)
Press share symbol at the bottom of your screen (chris, can you insert share symbol here)
Select “Add to Home Screen”
Press “Add” in the top right corner
- [x] Question: We want to collect user data about who uses the app/where. Do you know what kind of analytics data we could get? If its not much, we will think about adding a brief survey that has individuals share their name, email, and organization. 
- [x] Question: We want to collect user data about who uses the app/where. Do you know what kind of analytics data we could get? If its not much, we will think about adding a brief survey that has individuals share their name, email, and organization. 
- [x] Note: I am currently working on updating the MIND logo so it is not blurry. I cannot find the old logo anywhere, so I am starting from scratch and it will likely be a bit different than our current logo, but I will get it to you ASAP.
Thank you so much and please let me know if I can clarify anything.
