### ISSUE TITLE
Outstanding Questions

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#13]
**Outstanding Questions:**
---
- [x] **Finalize Data Schema:** - There are some differences between the sketch and the original database schema csv file.  Also, the schema structure has been slightly altered to provide for a more efficient client side implementation.  We also need to make a final decision on what data we are going to store, track, filter and display.  **No issues with the database schema**

    - [x] **Confirm New Schema Structure:** See [shared google sheets doc](https://docs.google.com/spreadsheets/d/1Kihd_Kx6lmRqBX508Wjh31vpNaZEa0GpEIXbyKgYSOk/edit?usp=sharing) or https://github.com/BIDMCDigitalPsychiatry/AppMapDB/issues/18 for more info.  Just looking for confirmation of the new structure and that it won't cause any issues on your end.  It differs slightly with naming conventions, field groupings and data types. **No issues with the database schema**

     - [x] **Determine Expected Database Size:** Do we have an idea of the number of applications that will be entered into the database?  If there are going to be more than 1k-2k applications, we may wan't to look at storing some of the database values as shortened enum string values.  This will reduce database size and network overhead, but probably isn't needed. **No issues with database size**

    - [x] **Resolve Discrepancies:** Between original CSV, Sketch and current implementation.   In this [shared google sheets doc](https://docs.google.com/spreadsheets/d/1Kihd_Kx6lmRqBX508Wjh31vpNaZEa0GpEIXbyKgYSOk/edit?usp=sharing) someone needs to go through and address all items that have "Needs Clarification" or "Please confirm" in the Implementation column.  The purpose of doing this is to remove any unnecessary/duplicated fields and align the db schema with the provided sketches.  There are a lot of fields, so we should ensure we only track the required/necessary fields.  Let me know if you want me to go through and do this or someone else that may be better equipped.

    - [x] **App MetaData:** As outlined in the above document, we need to determine if we are going to store app related metadata or look at alternative solutions.  As this information constantly changes and would require extensive effort to enter manually, it may make more sense to exclude it from the project or consider pulling the data directly from the app store using scraping libraries.

        **We will store the meta data from the web scraper library/API for each app store.**

    - [x] **Determine Table View Display:** There are quite a few existing fields in this table and we may be adding more from above.  We need to determine if/what fields will be displayed in this table.  Should we match the sketch only (current design) or display all fields?  Currently, we display limited columns and can add support for filtering on all data.  This seems like the best approach.  If the user needs additional information they can switch to the List View.  Any thoughts or considerations?
    - [x] **Determine List View Display:** Same as above, although this implementation will be easier to handle as we have less restrictions and more area to display all necessary data.
---
- [x] **Use App Store Scraping?:** There are a few libraries that allow extracting application information from the application store directly (see https://github.com/BIDMCDigitalPsychiatry/AppMapDB/issues/14).  Unfortunately, this cannot be called directly in the browser due to CORS, so if we want to use it in the browser we will need to have a backend server endpoint or a lambda function proxy the request.  We need to decide if we would like to use this or not.  If we don't use it, the user will need to enter in more information such as Application name, version, size, and upload an application photo and this information can change over time.  If this is a consideration, we should start some feasibility testing.  

    **Viability testing was completed and results were successful.  We will use app store scraping to obtain application meta information.  This is currently hosted in a google cloud function, but we are still determining the best approach for the CORS proxy implementation and the possibility of using existing Rest API's.**

---
- [x] **Application Images:** We need to determine if/how we are going to show/implement application images.  (See https://github.com/BIDMCDigitalPsychiatry/AppMapDB/issues/10 for more info).  

   **We will store the image url as part of the store meta data as this information is available via app scraping/api.**
