### ISSUE TITLE
Tasks/Roadmap (v2)

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#31]
**Current Progress**
--
- [x] The main page and search functionality has been updated to match new design.
- [x] The framework page has been updated to match the design.
- [x] Separated the My Ratings/Admin page into two tabs
    - [x] My Ratings: The user can start a new ratings and view/edit their existing (pending) ratings.
    - [x] Admin: A pending admin approval list has been implemented under the Admin tab.  This shows all pending approvals and allows easy maintenance by approving pending items or archiving items that are not needed.
    
- [x] Determine the necessary changes to the current list view and table views.  The current tables and list views are functional and re-designing them will take a decent amount of time.

- [x] For the table/list filtering, please confirm which option you would like.
   - [x] Leave the filter system as is.  It will work the same as it did before with the filters accessed via a button in the bottom right corner.
    - [x]  For larger screen sizes, add a section to the left of the table/list that shows the filters as outlined in the new design. For mobile screens, collapse the left section, but allow the user to open it via a button in the application bar header. **This appears to be the approach that is outlined in the Figma designs**    

- [x] Create/Update View App page to reflect the new design.

- [x] Redesign Rate an App workflow, with save draft and finish review functionality.

- [x] Update news implementation to reflect new design.  This is still TBD, some design work is still needed to determine the best approach.

**Documentation**
--
[Tech Assessment (Mind Tech)](https://drive.google.com/file/d/1Gkk5sZAyT6J3EBL5W-NtyOdp4NzKAwtd/view)
[Prototype](https://www.figma.com/proto/RMDX6NlZEmdvtF0b5FmWVC/Mind-website-HF?node-id=143%3A7393&viewport=599%2C450%2C0.04858091101050377&scaling=min-zoom)
[Figma](https://www.figma.com/file/RMDX6NlZEmdvtF0b5FmWVC/Mind-website-HF?node-id=1%3A3)
[Estimate/Questions](https://drive.google.com/file/d/1z0Kvmq9kRPCZND5bWF8IO5vXdRS10ah5/view?usp=sharing)

**Tasks**
--
- [x] (20 hours) Create New Layout and Associated Components
    - [x] (8 hours) Layout: Adjust existing components to match new design and change content from fixed height scrollable to non fixed height.
    - [x] (8 hours) Update application bar, footer, routing, login dialog.
- [x] (8 hours) Guidelines - Implement style guides and create buttons, tags, fonts, etc.
- [x] (8 hours) Update Dialogs: 
    - [x] Sign In
    - [x] Sign Up
    - [x] Confirm
    - [x] Forgot
    - [x] Reset Password
    - [x] Rate App.
- [x] (12 hours) Home Page/Find an App
    - [x] Create layout wireframe and sections.  Search area, search by features, search all, etc.
    - [x] Create search input component and connect filters and results.
- [x] (40 hours) - App Library
    - [x] (8hours) Create/Enhance Layout.  Impalement summary/title bar and update list view/table view toggle.
    - [x] (16 hours) Left Filter Bar - Existing filter inputs need to be moved and modified to accommodate the new layout.
    - [x] (4 hours) Update table view app name column to a fixed layout with a searchable header
    - [x] (4 hours) Update table styling to match new colors and background
    - [x] (8 hours) Various column component updates and remove unused columns and components.
- [x] (24 Hours) View App Page
    - [ ] Related Apps
    - [x] See Studies
    - [x] Read Review Dialog - Update to match new styling
- [x] (8 Hours) Rate an App Layout Page.  Your App Ratings, View App/Edit App, Start App Rating)
- [x] (32 Hours) Rate an App Page and Stepper - Migrate layout and create new input components and stepper logic.
- [x] (12 Hours) Rate an App Admin Page (Pending, Archived, etc)
- [x] (12 Hours) Framework - Create/adapt content to new layout and styling.
- [x] (12 hours) News
    - [x] (6 hours) Create tiled layout
    - [x] (6 hours) Create view more page
- [x] (12 hours) Mobile Layouts - Create/test mobile layouts and fix any issues.
- [x] (16 hours) Misc Tasks/Revisions

**Outstanding Questions**
--
- [x] The app library tables in the new design use paging. This differs from the original design.
Either method is viable but we should confirm which implementation is desired before
implementing. With virtual scrolling you get a fixed height inner content window and the
user never has to hit the next or previous page buttons. With paging, the height of the
window is determined by the length of the content.
**I'm not totally sure here - which do you think is easier for users/most versatile on web,
phone, etc?**  At this point, I think it will be best to stick to virtual scrolling implementations as that works better on when using multiple platform screen sizes (phone/desktop).  If there are any obvious advantages migrating to a paged view that are encountered during development, we will re-evaluate.

- [x] Has any consideration been given to the implementation of the news section or how that
content will be managed? This can affect the development time drastically. A simple
solution would be to use a third party tool or the existing workflow (modify github files) that
is used for framework & questions, etc.
**I think simplest would be best. We want the news section to be easily editable such that
content (generally a short blog style entry with accompanying picture) can be regularly
added. How easy do you think this would be with the existing workflow (modify github
files)?**  This is TBD.

- [x] The MindTech assessment document details a bunch of technologies that are not
currently used. Most notable is the use of Angular instead of React, which would require
significant migration efforts. Is there a reason for changing/ using these technologies? I
could make various arguments/suggestions here, but not sure if it is needed at this time or
if this document is relevant. Let me know if we need to discuss in further detail?
**I'll defer to you here - at this point I don't think migration efforts are necessary and we are
totally fine sticking with the current technologies.**  Ok, I will adjust as necessary, but we will stick with current technologies to ensure this project remains on budget and on track.

- [x] Is pixel perfect design needed or is close as possible is acceptable?  **Close as possible" sounds great, no need for perfect pixel design.**

**Comment by cvanem** [comment]
Tech Assessment (Mind Tech) https://drive.google.com/file/d/1Gkk5sZAyT6J3EBL5W-NtyOdp4NzKAwtd/view
