### ISSUE TITLE
Add Supported Conditions

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#98]
**TODO**
- [x] Add "non-specific" supported condition
- [x] Substance Use (Alcohol)
- [x] Substance Use (Smoking & Tobacco)

-------
**Original Content**

Add "non-specific" as a category under supported conditions

Also when you click substance use we would like it to still pull up all substance use apps, but then a drop down appear which specifies "Alcohol" and "Smoking & Tobacco" 
- doesn't necessarily need to be a drop down but maybe an indentation so people know it's under substance use

be sure this condition is added to the rating section as well as the filter on the left hand side

**Comment by cvanem** [comment]
@ecamach13 
The current code and database schema is not designed to support "sub-categories" for supported conditions, so something like this would take a large amount of effort and design modifications. 

Is there an alternate solution that would work?  Can we just add two additional supported conditions for:
Substance Abuse (Alcohol) 
Substance Abuse (Smoking & Tabaco)

Will this work?  This would be easy to implement and still allow the search behavior you describe above.

**Comment by ecamach13** [comment]
Yes that works! 

The correct phrasing should be: 
Substance Use (Alcohol)
Substance Use (Smoking & Tobacco) 

If we change this, what happens to the apps that are currently labeled Substance Use? Will they still be in the database but without a supported condition connected? Then I can go back and add that supported condition?

**Comment by cvanem** [comment]
@ecamach13 
We would just be adding two additional conditions, so the original "Substance Abuse" condition would remain as is.  The apps that are currently labeled Substance Use will continue to have that label.  If you want them to also have a Substance Use (Alcohol) or Substance Use (Smoking & Tabaco) label, a new or edited rating would need to be submitted which has those selected.

**Comment by ecamach13** [comment]
I'm not seeing these added conditions even when I Ctrl+F5

**Comment by cvanem** [comment]
@ecamach13 When I push a commit, the automated build process starts.  The green check box in the picture below means the build was successful.  After that happens there is a few minutes delay until the changes go live.    I just checked and the changes are now live.


![image](https://user-images.githubusercontent.com/24579103/123146662-60e8b100-d41b-11eb-9887-5db18ff97e90.png)

**Comment by ecamach13** [comment]
Ohhh, I see! Thank you!
